### PR TITLE
Fix CGroup parsing for non-containerized environment.

### LINKED ISSUE #1475: Error while parsing container info. Cause: undefined method `[]' for nil:NilClass
Since upgrading to 0.48, several of our developers running linux are running into the following error when starting up the app:

```ERROR -- ddtrace: [ddtrace] (/home/mscrivo/affinity/vendor/bundle/ruby/3.0.0/gems/ddtrace-0.48.0/lib/ddtrace/runtime/container.rb:71:in `rescue in block in descriptor') Error while parsing container info. Cause: undefined method `[]' for nil:NilClass Location: /home/mscrivo/affinity/vendor/bundle/ruby/3.0.0/gems/ddtrace-0.48.0/lib/ddtrace/runtime/container.rb:56:in `block (2 levels) in descriptor'```

Even if tracing is disabled. Note, they are running the code on VMs, but not containers. Downgrading to 0.47 gets rid of the error.  People using macOS don't see this.

Ruby version: 3.0

### PR DESCRIPTION
**Pull request by delner**
Fixes #1475 

Our container parsing code was raising an error when encountering cgroup paths that weren't in containerized environments; although the defensive measure in place was working as intended, this pull request prevents that error and makes CI assert no such error is raised.

### CODE REVIEW

**Comment by delner** [comment]
Thanks to @collinsauve for his contribution orignally in #1476! Added it to this PR.

**Review by ericmustin — APPROVED** [review]

**Review by marcotc — APPROVED** [review]
