### PR TITLE
APMS-15322 Reproducer for loading core only and configuring the library

### PR DESCRIPTION
**Pull request by p-datadog**
**What does this PR do?**

Adds a test that the tracer can be configured when only core part of the code is loaded.

Also adds a require from tracing to its contrib to avoid leaking tracing internals to core/customers.

**Motivation:**

A customer reported an exception when initializing dd-trace-rb 2.12.2 which I was able to reproduce with the following code:
```
require 'datadog/core'
require 'datadog/tracing/contrib'

Datadog.configure do
end
```

The above code worked on 2.4.0 and is failing from 2.5.0 through 2.12.2 with the following exception:
```
/home/w/apps/dd-trace-rb/lib/datadog/core/remote/transport/http.rb:105:in `block in default_headers': undefined method `appsec' for an instance of Datadog::Core::Configuration::Settings (NoMethodError)

              if Datadog.configuration.appsec.standalone.enabled
                                      ^^^^^^^
	from <internal:kernel>:90:in `tap'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/remote/transport/http.rb:99:in `default_headers'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/remote/transport/http.rb:47:in `block in root'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/transport/http/builder.rb:37:in `initialize'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/transport/http.rb:33:in `new'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/transport/http.rb:33:in `build'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/remote/transport/http.rb:34:in `new'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/remote/transport/http.rb:45:in `root'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/environment/agent_info.rb:58:in `initialize'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration/components.rb:104:in `new'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration/components.rb:104:in `initialize'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:253:in `new'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:253:in `build_components'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:92:in `block in configure'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:235:in `block in safely_synchronize'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:233:in `synchronize'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:233:in `safely_synchronize'
	from /home/w/apps/dd-trace-rb/lib/datadog/core/configuration.rb:87:in `configure'
	from /home/w/apps/dd-trace-rb/lib/datadog/tracing/contrib/extensions.rb:66:in `configure'
	from repro.rb:4:in `<main>'
```

The issue causing the exception is already repaired on master (via https://github.com/DataDog/dd-trace-rb/pull/4498) however there was no existing test coverage for this particular usage of the library, which the present PR is now adding.

**Change log entry**
None for this PR, however https://github.com/DataDog/dd-trace-rb/pull/4498 also repairs the failure to configure dd-trace-rb which I added to its change log entry.

**Additional Notes:**

**How to test the change?**
Test added in this PR

### CODE REVIEW

**Comment by p-datadog** [comment]
Type checking failure repaired in https://github.com/DataDog/dd-trace-rb/pull/4545

**Review by sarahchen6 — APPROVED** [review]
