### PR TITLE
[NO-TICKET] Fix AppSec devise contrib raising on non-standard Warden session serialization

### LINKED ISSUE #6063: AppSec Devise tracking_middleware raises TypeError (HTTP 500 every request) on non-standard Warden session serialization
## Summary

`AppSec::Contrib::Devise::TrackingMiddleware#extract_id` assumes the value Devise
stores in the Warden session is the standard `[[id], salt]` shape and calls
`dig(0, 0)` on it. When an application uses a custom
`Warden::SessionSerializer#serialize_into_session` (or a non-Devise Warden
strategy) that stores a different shape, `dig(0, 0)` raises and **every request
routed through the middleware returns HTTP 500**, because AppSec's auto user
instrumentation runs on every request for an authenticated session.

The safe-navigation operator (`&.dig`) only guards `nil` — it does not guard a
value that responds to `#dig` but cannot be dug two levels deep.

## Affected code

`lib/datadog/appsec/contrib/devise/tracking_middleware.rb` (`#extract_id`, two call sites):

```ruby
id = session_serializer.session[key]&.dig(0, 0)
```

Introduced in #4625 ("Add session tracking and fingerprinting"), first released in **v2.16.0**.

## Steps to reproduce

With `config.appsec.auto_user_instrumentation.mode = 'identification'` (or `'anonymization'`)
and a Warden session serializer that stores the authenticatable key as a flat array, e.g.
`serialize_into_session { |record| [record.id] }`, the stored value is `[id]`.

```ruby
[42].dig(0, 0)
# => TypeError: Integer does not have #dig method
```

`Array#dig` recurses: `dig(0)` returns the Integer `42`, then it calls `.dig(0)` on `42`, which raises.

A bare-id serializer (`serialize_into_session { |r| r.id }`) raises a related error:

```ruby
42.dig(0, 0)
# => NoMethodError: undefined method `dig' for an instance of Integer
```

## Expected behavior

Non-standard session shapes should disable auto id extraction for that request
(return `nil`, skip tracking) — never raise and 500 the request.

## Actual behavior

Unhandled `TypeError`/`NoMethodError` inside the middleware on every request for an
affected session, returning HTTP 500. Observed on authenticated pages and on
`/oauth/authorize`.

## Errors (stack trace)

```
TypeError: Integer does not have #dig method
  …/datadog/appsec/contrib/devise/tracking_middleware.rb:70:in `extract_id'
```

## Configuration

- `datadog` version: **2.38.0** (regression present since 2.16.0)
- Ruby: reproducible on any supported Ruby (the failure is a session-shape mismatch, not version-specific)
- Relevant gems: `devise`, `warden` (with a custom `serialize_into_session`)
- `config.appsec.auto_user_instrumentation.mode = 'identification'`

## Suggested fix

Only extract the id from the shape Devise itself writes (`[[id], salt]`); return
`nil` for any other shape instead of calling `dig` blindly. PR attached.

## Workaround

Set `config.appsec.auto_user_instrumentation.mode = 'disabled'`
(or `DD_APPSEC_AUTO_USER_INSTRUMENTATION_MODE=disabled`) — this short-circuits the
middleware before `extract_id` and leaves the rest of AppSec (WAF) intact.

### PR DESCRIPTION
**Pull request by nsinenko**
### What does this PR do?

Makes `AppSec::Contrib::Devise::TrackingMiddleware#extract_id` tolerant of
non-standard Warden session serializations. It extracts the authenticatable id
only from the shape Devise writes (`[[id], salt]`) and returns `nil` for any
other shape, instead of calling `dig(0, 0)` and raising.

### Motivation

Auto user instrumentation runs on every request. When an application overrides
`Warden::SessionSerializer#serialize_into_session` (or uses a non-Devise Warden
strategy) and stores e.g. a flat `[id]`, `session[key]&.dig(0, 0)` raises
`TypeError: Integer does not have #dig method` (`Array#dig` recursing into an
Integer), turning **every authenticated request into an HTTP 500**. `&.` only
guards `nil`, not a value that responds to `#dig` but is not diggable two levels
deep.

Regression introduced in #4625, released in v2.16.0.

Fixes #6063.

### Change log entry

Yes. Fix error in `devise` contrib for non-standard Warden session serialization.

### How to test the change?

Added a unit spec for `#extract_id` covering the standard `[[id], salt]` shape
plus the flat-array, bare-id, and nil shapes (the last three must not raise and
must return `nil`). CI.

### Additional notes

For apps hitting this on a released version, the immediate workaround is
`config.appsec.auto_user_instrumentation.mode = 'disabled'`.

Closes #6067

### CODE REVIEW

File: spec/datadog/appsec/contrib/devise/tracking_middleware_spec.rb [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+    let(:session_serializer) do
+      double('Warden::SessionSerializer', session: {'warden.user.user.key' => serialized})
+    end
+
+    before do
+      allow(session_serializer).to receive(:key_for).and_return('warden.user.user.key')
+
+      # Single Devise mapping (default scope only).
+      stub_const('Devise', Module.new)
+      allow(Devise).to receive(:default_scope).and_return(:user)
```
[the remark this answers is not in the document]
Comment (nsinenko) [reply spec/datadog/appsec/contrib/devise/tracking_middleware_spec.rb]: Good catch — fixed. The spec no longer replaces the `Devise` constant with a bare `Module.new`. It now `require`s the real `devise` gem and partial-stubs the genuine `Devise.default_scope` / `Devise.mappings` (both real methods — production `TrackingMiddleware#extract_id` calls `::Devise.default_scope`, and the sibling `data_extractor_spec.rb` already partial-stubs `Devise.mappings` under the same `verify_partial_doubles = true`). All test doubles are now `instance_double(Warden::Proxy | Warden::SessionSerializer | Devise::Mapping)`, so `verify_partial_doubles` is satisfied.

Addressed in the (now squashed) head commit `b401b32`.

File: lib/datadog/appsec/contrib/devise/tracking_middleware.rb [hunk 2]
```diff
@@ -76,14 +76,34 @@ def extract_id(warden)
...
+          # so the authenticatable id lives at `[0][0]`. Applications may
+          # override `Warden::SessionSerializer#serialize_into_session` (or use
+          # a non-Devise Warden strategy) and store a different shape - a flat
+          # `[id]`, a bare id, a Hash, etc. Calling `dig(0, 0)` on those raises
+          # and turns every request into a 500 - e.g. `[id].dig(0, 0)` makes
+          # `Array#dig` recurse into an Integer and raise
+          # `TypeError: Integer does not have #dig method`. We can only reliably
+          # recover the id from the shape Devise itself writes, so any other
+          # shape yields `nil` (auto-tracking is skipped) instead of raising.
+          def authenticatable_id(serialized)
```
Comment (Strech) [inline lib/datadog/appsec/contrib/devise/tracking_middleware.rb]: I would suggest name with a verb here and session as a subject


```suggestion
          def extract_record_id(session)
```

or something similar, like `extract_user_id`, or so

File: lib/datadog/appsec/contrib/devise/tracking_middleware.rb [hunk 3]
```diff
@@ -76,14 +76,34 @@ def extract_id(warden)
...
+          # `[record.to_key, authenticatable_salt]` (e.g. `[[1], "0abc..."]`),
+          # so the authenticatable id lives at `[0][0]`. Applications may
+          # override `Warden::SessionSerializer#serialize_into_session` (or use
+          # a non-Devise Warden strategy) and store a different shape - a flat
+          # `[id]`, a bare id, a Hash, etc. Calling `dig(0, 0)` on those raises
+          # and turns every request into a 500 - e.g. `[id].dig(0, 0)` makes
+          # `Array#dig` recurse into an Integer and raise
+          # `TypeError: Integer does not have #dig method`. We can only reliably
+          # recover the id from the shape Devise itself writes, so any other
+          # shape yields `nil` (auto-tracking is skipped) instead of raising.
```
Comment (Strech) [inline lib/datadog/appsec/contrib/devise/tracking_middleware.rb]: I would like to ask for a very concise comment here, that in short explain the shape and do not explain the code issues, preferable non-ai generated, i.e this could be removed

```
# Calling `dig(0, 0)` on those raises
# and turns every request into a 500 - e.g. `[id].dig(0, 0)` makes
# `Array#dig` recurse into an Integer and raise
# `TypeError: Integer does not have #dig method`. We can only reliably
# recover the id from the shape Devise itself writes, so any other
# shape yields `nil` (auto-tracking is skipped) instead of raising.
```

File: spec/datadog/appsec/contrib/devise/tracking_middleware_spec.rb [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+
+require 'devise'
+require 'datadog/appsec/spec_helper'
+require 'datadog/appsec/contrib/devise/tracking_middleware'
+
+RSpec.describe Datadog::AppSec::Contrib::Devise::TrackingMiddleware do
+  let(:middleware) { described_class.new(->(_env) { [200, {}, ['OK']] }) }
+
+  describe '#extract_id' do
+    subject(:extract_id) { middleware.send(:extract_id, warden) }
```
Comment (Strech) [inline spec/datadog/appsec/contrib/devise/tracking_middleware_spec.rb]: Since that is a private call, it's better to use integration tests (already in place) to test that a correct span tag will be assigned with ID and also by introducing the failing spec you could see red-green behavior of tests.

**Review by Strech — COMMENTED** [review]
Hey @nsinenko, thanks a lot for your contribution, nice catch!

I would like to ask for small changes in the code and different direction in the test-suite.

If you don't feel that you have capacity, please let me know and I can push changes directly into the PR's branch.

File: lib/datadog/appsec/contrib/devise/tracking_middleware.rb (hunk 2 above)
Comment (nsinenko) [reply lib/datadog/appsec/contrib/devise/tracking_middleware.rb]: Renamed to `extract_record_id` as per your suggestion.

File: lib/datadog/appsec/contrib/devise/tracking_middleware.rb (hunk 3 above)
Comment (nsinenko) [reply lib/datadog/appsec/contrib/devise/tracking_middleware.rb]: Thanks for suggestion. Updated.

File: spec/datadog/appsec/contrib/devise/tracking_middleware_spec.rb (hunk 4 above)
Comment (nsinenko) [reply spec/datadog/appsec/contrib/devise/tracking_middleware_spec.rb]: Thanks. Removed this specs and added an integration test.

**Comment by nsinenko** [comment]
> Hey @nsinenko, thanks a lot for your contribution, nice catch!
> 
> I would like to ask for small changes in the code and different direction in the test-suite.
> 
> If you don't feel that you have capacity, please let me know and I can push changes directly into the PR's branch.

Thanks @Strech for a review. I've updated on your review feedback. If you think more changes are needed feel free to push directly. 

Would love to have this live as this was blocking us from upgrading the gem to a newer version.

**Comment by Strech** [comment]
> Would love to have this live as this was blocking us from upgrading the gem to a newer version.

Ok, I can help with that, also will drive the release to happen this week

**Review by Strech — APPROVED** [review]
