### ISSUE TITLE
v0.35.0: NoMethodError 'close' when running Rails migrations

### ISSUE THREAD

**Issue by jtannas** [DataDog/dd-trace-rb#1024]
## Error Information:
After updating to v0.35.0 last night, running `rake db:migrate` results in a NoMethodError at the end of the migrations.

Stack Trace:
```
/usr/src/backend # rake db:migrate
   (0.1ms)  SELECT pg_try_advisory_lock(5179685882595929775)
   (0.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ActiveRecord::InternalMetadata Load (0.3ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
   (0.2ms)  SELECT pg_advisory_unlock(5179685882595929775)
   (0.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Traceback (most recent call last):
	3: from /usr/local/bundle/ruby/2.7.0/gems/ddtrace-0.35.0/lib/ddtrace.rb:37:in `block in <module:Datadog>'
	2: from /usr/local/bundle/ruby/2.7.0/gems/ddtrace-0.35.0/lib/ddtrace/configuration.rb:44:in `shutdown!'
	1: from /usr/local/bundle/ruby/2.7.0/gems/ddtrace-0.35.0/lib/ddtrace/configuration/components.rb:150:in `teardown!'
/usr/local/bundle/ruby/2.7.0/gems/ddtrace-0.35.0/lib/ddtrace/configuration/components.rb:150:in `each': undefined method `close' for nil:NilClass (NoMethodError)
```

## Tech Stack Information:
[dockerfile_and_gems.zip](https://github.com/DataDog/dd-trace-rb/files/4582444/dockerfile_and_gems.zip)

Configfile:
```ruby
# frozen_string_literal: true

require 'ddtrace'

Datadog.configure do |c|
  # This will activate auto-instrumentation for Rails
  c.tracer enabled: Rails.env.production?
  c.use :rails, analytics_enabled: Rails.env.production?
  c.use :active_record, analytics_enabled: Rails.env.production?, service_name: 'postgresql'
end

```

**Comment by delner** [comment]
This is a duplicate of #1021, which has been resolved by #1023. It will be deployed in a bugfix release very soon.
