### ISSUE TITLE
error message undefined method `resource=' for nil:NilClass after updated from 0.54.2 to 1.1.0

### ISSUE THREAD

**Issue by kaku0225** [DataDog/dd-trace-rb#2093]
**Current behaviour**

after I updated to 1.1.0, the following message appeared in my CI

```
...........E, [2022-06-17T15:26:19.031161 #9765] ERROR -- ddtrace: [ddtrace] (/home/travis/build/minkabu/kabutan_usa/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.1.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:43:in `rescue in start_processing') undefined method `resource=' for nil:NilClass
              trace.resource = span.resource
                   ^^^^^^^^^^^
E, [2022-06-17T15:26:19.035984 #9765] ERROR -- ddtrace: [ddtrace] (/home/travis/build/minkabu/kabutan_usa/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.1.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:79:in `rescue in finish_processing') undefined method `resource=' for nil:NilClass
                trace.resource = span.resource
                     ^^^^^^^^^^^
.E, [2022-06-17T15:26:19.070883 #9765] ERROR -- ddtrace: [ddtrace] (/home/travis/build/minkabu/kabutan_usa/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.1.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:43:in `rescue in start_processing') undefined method `resource=' for nil:NilClass
              trace.resource = span.resource
                   ^^^^^^^^^^^
E, [2022-06-17T15:26:19.076904 #9765] ERROR -- ddtrace: [ddtrace] (/home/travis/build/minkabu/kabutan_usa/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.1.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:79:in `rescue in finish_processing') undefined method `resource=' for nil:NilClass
                trace.resource = span.resource
                     ^^^^^^^^^^^
```

**Expected behaviour**

these messages do not appear

**Environment**

* **ddtrace version:** 1.1.0
* **Configuration block (`Datadog.configure ...`):**
```
Datadog.configure do |c|
  # Global settings
  c.tracing.enabled = (ENV["DD_TRACE_ENABLED"].to_s.downcase == "true")
  c.env = Rails.env
  c.tracing.log_injection = false
  # Instrumentation
  c.tracing.instrument :rails,   service_name: "main"
  c.tracing.instrument :redis,   service_name: "main-redis"
  c.tracing.instrument :http,    service_name: "main-http"
  c.tracing.instrument :sidekiq, service_name: "main-sidekiq"
end
```
* **Ruby version:** 3.1.2

**Comment by kaku0225** [comment]
I found this issue fixed in this [PR](https://github.com/DataDog/dd-trace-rb/pull/2027)
and this PR has not been released yet
