### ISSUE TITLE
1.16.0: undefined method `to_digest' for nil:NilClass

### ISSUE THREAD

**Issue by mscrivo** [DataDog/dd-trace-rb#3244]
**Current behaviour**
Our shoryuken workers are crashing with the above error after upgrading to 1.16

This seems to have been introduced in [this](https://github.com/DataDog/dd-trace-rb/commit/f3e4f7ea1b91da81f677f90b61f7e265134335d2) commit, which is not safely checking for the existence of active_trace.

**Expected behaviour**
No crash

**Steps to reproduce**
Run a shoryuken worker with tracing enabled

**Environment**

* **ddtrace version:** 1.16.0
* **Configuration block (`Datadog.configure ...`):** pretty standard config
* **Ruby version:** 3.2.2
* **Operating system:** linux

stack trace of error:
```
vendor/bundle/ruby/3.2.0/gems/ddtrace-1.16.0/lib/datadog/tracing/contrib/concurrent_ruby/context_composite_executor_service.rb:22:in `post': undefined method `to_digest' for nil:NilClass (NoMethodError)

            digest = Tracing.active_trace.to_digest
                                         ^^^^^^^^^^
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:55:in `execute'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:78:in `execute'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/lib/shoryuken/launcher.rb:65:in `block in start_managers'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/lib/shoryuken/launcher.rb:64:in `each'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/lib/shoryuken/launcher.rb:64:in `start_managers'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/lib/shoryuken/launcher.rb:13:in `start'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/lib/shoryuken/runner.rb:43:in `run'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/bin/shoryuken:42:in `start'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
	from /home/affinity/vendor/bundle/ruby/3.2.0/gems/shoryuken-6.1.0/bin/shoryuken:53:in `<top (required)>'
	from /home/affinity/vendor/bundle/ruby/3.2.0/bin/shoryuken:25:in `load'
	from /home/affinity/vendor/bundle/ruby/3.2.0/bin/shoryuken:25:in `<top (required)>'
```

**Comment by ivoanjo** [comment]
Hey @mscrivo sorry that we missed this one! We have a PR up for it (#3242) and are preparing to ship a 1.16.1 with the fix.

**Comment by etagwerker** [comment]
I just ran into this issue when running rake assets:precompile. Would love to get my hands on 1.16.1 when it ships. 😄
