### ISSUE TITLE
Warning printed when using rails_semantic_logger's hash-based log_tags

### ISSUE THREAD

**Issue by lucthev** [DataDog/dd-trace-rb#3016]
After upgrading to 1.13.0, I'm seeing a (false) warning in an app using `rails_semantic_logger` and its somewhat unusual [hash-based `log_tags`](https://logger.rocketjob.io/rails#named-tags):

```
W, [2023-07-31T17:56:28.916763 #71347]  WARN -- ddtrace: [ddtrace] Unable to add Datadog Trace context to ActiveSupport::TaggedLogging: NoMethodError undefined method `<<' for {:ip=>:remote_ip}:Hash
```

Coming from this code, which understandably fails when `log_tags` is a hash:

https://github.com/DataDog/dd-trace-rb/blob/b3f3a0a4b9f397724c87750d7764cfdc54ecd647/lib/datadog/tracing/contrib/rails/log_injection.rb#L13

This method of log tag injection appears to be unnecessary when using `rails_semantic_logger`, as Datadog injects trace tags [via other means](https://github.com/DataDog/dd-trace-rb/blob/b3f3a0a4b9f397724c87750d7764cfdc54ecd647/lib/datadog/tracing/contrib/semantic_logger/instrumentation.rb#L17-L46), at the individual log level — despite the warning, logs produced by `rails_semantic_logger` have the correct `dd` trace tags.

**Current behaviour**

The above warning.

**Expected behaviour**

No warning.

**Steps to reproduce**

I've created a [sample app](https://github.com/lucthev/ddtrace-log-warning-repro/tree/main) to demonstrate the issue. The relevant bits are https://github.com/lucthev/ddtrace-log-warning-repro/compare/5cf860ba23713bdf9072061911661abc85133166...main.

Simply run `rails s` and a warning should be printed.

**Comment by marcotc** [comment]
Thank you for the quick upgrade, and the detailed issue report, @lucthev!

Seems like a combination of configurations that can be common.

> despite the warning, logs produced by rails_semantic_logger have the correct dd trace tags.

This is reassuring, we'll work on a fix shortly!

**Comment by marcotc** [comment]
Fix is done, will be released in the next version of `ddtrace`: https://github.com/DataDog/dd-trace-rb/pull/3022

We'll update this issue when the release is out.
