### ISSUE TITLE
AppSec Devise tracking_middleware raises TypeError (HTTP 500 every request) on non-standard Warden session serialization

### ISSUE THREAD

**Issue by nsinenko** [DataDog/dd-trace-rb#6063]
## Summary

`AppSec::Contrib::Devise::TrackingMiddleware#extract_id` assumes the value Devise
stores in the Warden session is the standard `[[id], salt]` shape and calls
`dig(0, 0)` on it. When an application uses a custom
`Warden::SessionSerializer#serialize_into_session` (or a non-Devise Warden
strategy) that stores a different shape, `dig(0, 0)` raises and **every request
routed through the middleware returns HTTP 500**, because AppSec's auto user
instrumentation runs on every request for an authenticated session.

The safe-navigation operator (`&.dig`) only guards `nil` — it does not guard a
value that responds to `#dig` but cannot be dug two levels deep.

## Affected code

`lib/datadog/appsec/contrib/devise/tracking_middleware.rb` (`#extract_id`, two call sites):

```ruby
id = session_serializer.session[key]&.dig(0, 0)
```

Introduced in #4625 ("Add session tracking and fingerprinting"), first released in **v2.16.0**.

## Steps to reproduce

With `config.appsec.auto_user_instrumentation.mode = 'identification'` (or `'anonymization'`)
and a Warden session serializer that stores the authenticatable key as a flat array, e.g.
`serialize_into_session { |record| [record.id] }`, the stored value is `[id]`.

```ruby
[42].dig(0, 0)
# => TypeError: Integer does not have #dig method
```

`Array#dig` recurses: `dig(0)` returns the Integer `42`, then it calls `.dig(0)` on `42`, which raises.

A bare-id serializer (`serialize_into_session { |r| r.id }`) raises a related error:

```ruby
42.dig(0, 0)
# => NoMethodError: undefined method `dig' for an instance of Integer
```

## Expected behavior

Non-standard session shapes should disable auto id extraction for that request
(return `nil`, skip tracking) — never raise and 500 the request.

## Actual behavior

Unhandled `TypeError`/`NoMethodError` inside the middleware on every request for an
affected session, returning HTTP 500. Observed on authenticated pages and on
`/oauth/authorize`.

## Errors (stack trace)

```
TypeError: Integer does not have #dig method
  …/datadog/appsec/contrib/devise/tracking_middleware.rb:70:in `extract_id'
```

## Configuration

- `datadog` version: **2.38.0** (regression present since 2.16.0)
- Ruby: reproducible on any supported Ruby (the failure is a session-shape mismatch, not version-specific)
- Relevant gems: `devise`, `warden` (with a custom `serialize_into_session`)
- `config.appsec.auto_user_instrumentation.mode = 'identification'`

## Suggested fix

Only extract the id from the shape Devise itself writes (`[[id], salt]`); return
`nil` for any other shape instead of calling `dig` blindly. PR attached.

## Workaround

Set `config.appsec.auto_user_instrumentation.mode = 'disabled'`
(or `DD_APPSEC_AUTO_USER_INSTRUMENTATION_MODE=disabled`) — this short-circuits the
middleware before `extract_id` and leaves the rest of AppSec (WAF) intact.

**Comment by Strech** [comment]
Hey @nsinenko thanks a lot for the fix, let's discuss it inside the PR. Awesome catch! 🤝
